### ISSUE TITLE
.pre-commit-hooks.yaml file is missing

### ISSUE THREAD

**Issue by marcindulak** [gaurav-nelson/asciidoc-link-check#34]
To reproduce

```
cat .pre-commit-config.yaml
repos:
- repo: https://github.com/gaurav-nelson/asciidoc-link-check
  # See https://pre-commit.com/#using-the-latest-version-for-a-repository
  rev: master
  hooks:
    - id: asciidoc-link-check
      entry: asciidoc-link-check --config .mlc_config.json
      args: [-q]
```

```
pre-commit install
```

```
pre-commit run --all-files
...
An error has occurred: InvalidManifestError: 
=====> /Users/user/.cache/pre-commit/repon9gtkl4j/.pre-commit-hooks.yaml is not a file
Check the log at /Users/user/.cache/pre-commit/pre-commit.log
```

This is because the `.pre-commit-hooks.yaml` file is missing. It can be added analogously to https://github.com/tcort/markdown-link-check/commit/6095b285e39a0b019a49a241e131ae1828d53ca8
