### ISSUE TITLE
asciidoc-link-check in pre-commit gives TypeError: program.option is not a function

### ISSUE THREAD

**Issue by marcindulak** [gaurav-nelson/asciidoc-link-check#37]
To reproduce in a pre-commit setup

```
cat .pre-commit-config.yaml
repos:
- repo: https://github.com/gaurav-nelson/asciidoc-link-check
  # See https://pre-commit.com/#using-the-latest-version-for-a-repository
  rev: master
  hooks:
    - id: asciidoc-link-check
```

```
pre-commit install
```

```
pre-commit run --all-files
...
```

Output

```
/Users/test/.cache/pre-commit/repoof0ld2je/node_env-system/lib/node_modules/asciidoc-link-check/asciidoc-link-check:31
  .option("-p, --progress", "show progress bar")
   ^

TypeError: program.option is not a function
    at Object.<anonymous> (/Users/test/.cache/pre-commit/repoof0ld2je/node_env-system/lib/node_modules/asciidoc-link-check/asciidoc-link-check:31:4)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.6.1
```

I'm not able to reproduce this problem locally in the asciidoc-link-check repo, despite using the same node version
```
node --version
npm ci
./asciidoc-link-check test.md
```
